### PR TITLE
Update Dockerfile with new Tizen Studio Version 4.6

### PR DESCRIPTION
**Pull request by ionescu77**
## Increment Tizen Studio Version from 4.1.1 to 4.6

Hi @vitalets , great work here, thank you.

Just incrementing Tizen Studio to `4.6`

Screenshot 2022-10-13 at 16 34 14

I'm still trying to see how to set the proper paths in order to compile my angular project from `dist` into a `wgt`, but your README.ms is great.

I'll dig in!

### CODE REVIEW

**Comment by vitalets** [comment]
@pfilatov92 @stamoern Hey guys! Maybe take leadership for this repo? )

**Comment by pfilatov92** [comment]
> @pfilatov92 @stamoern Hey guys! Maybe take leadership for this repo? )

Sure. I can take it :)

**Comment by vitalets** [comment]
@pfilatov92 invite sent

**Comment by vitalets** [comment]
Just released [v3.0](https://hub.docker.com/repository/docker/vitalets/tizen-webos-sdk/tags?page=1&ordering=last_updated) with the latest Tizen Studio and WebOS CLI.
Closing this.

**Pull request closed without merging**
